#!/usr/bin/env python3
"""Hardcoded-style ratchet for the Flutter UI layers.

The design system lives in `flutter_app/lib/design/` (tokens + palette +
shells). Every numeric style literal written outside it — `Color(0x...)`,
`fontSize: 13`, `EdgeInsets.all(20)` — is a site that a token change cannot
reach, so the upgrade silently stops applying there. This script counts those
sites per file and fails when any count rises above the stored baseline.

It is a ratchet, not a linter: lowering a count never fails, and the baseline
is expected to shrink as pages migrate. Regenerate it with `--update` after
cleaning a file.

Run: `python scripts/check_design_style.py [--update|--report]`
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LIB = ROOT / "flutter_app" / "lib"
BASELINE = ROOT / "scripts" / "design_style_baseline.json"

# UI layers that must consume the design system. `lib/design/` is excluded:
# it owns the literal values the tokens exist to replace.
SCAN_DIRS = ("screens", "widgets")

PATTERNS = {
    "hexColor": re.compile(r"Color\(0x[0-9A-Fa-f]"),
    "fontSize": re.compile(r"fontSize:\s*[\d.]"),
    "radius": re.compile(r"(?<![A-Za-z])(?:Border)?Radius\.[a-zA-Z]+\(\s*[\d.]"),
    "insets": re.compile(r"EdgeInsets\.[a-zA-Z]+\(\s*[\d.]"),
    "alpha": re.compile(r"\.with(?:Values\(\s*alpha|Opacity)\(\s*[\d.]"),
    "duration": re.compile(r"Duration\(\s*milliseconds:\s*\d"),
}

# Comment text carries hex values from the Ardot hand-off notes; counting it
# would make the baseline move on documentation edits.
LINE_COMMENT_RE = re.compile(r"(?<![:\\])//.*$")


def strip_comments(text):
    return "\n".join(LINE_COMMENT_RE.sub("", line) for line in text.splitlines())


def count_file(path):
    counts = {name: 0 for name in PATTERNS}
    text = strip_comments(path.read_text(encoding="utf-8"))
    for name, pattern in PATTERNS.items():
        counts[name] = len(pattern.findall(text))
    return {name: value for name, value in counts.items() if value}


def collect():
    measured = {}
    for folder in SCAN_DIRS:
        base = LIB / folder
        if not base.exists():
            continue
        for path in sorted(base.rglob("*.dart")):
            counts = count_file(path)
            if counts:
                measured[path.relative_to(ROOT).as_posix()] = counts
    return measured


def load_baseline():
    if not BASELINE.exists():
        return {}
    data = json.loads(BASELINE.read_text(encoding="utf-8"))
    return data.get("files", data)


def write_baseline(measured):
    total = sum(c for counts in measured.values() for c in counts.values())
    payload = {
        "_comment": "Generated by scripts/check_design_style.py --update. "
        "Numeric style literals outside lib/design/; lower is better.",
        "total": total,
        "files": measured,
    }
    BASELINE.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(f"Baseline written: {BASELINE.relative_to(ROOT)} ({total} sites)")


def report(measured):
    rows = sorted(
        ((sum(counts.values()), path, counts) for path, counts in measured.items()),
        reverse=True,
    )
    print(f"{'sites':>6}  file")
    for total, path, counts in rows[:15]:
        detail = " ".join(f"{k}:{v}" for k, v in sorted(counts.items()))
        print(f"{total:>6}  {path}  {detail}")
    print(f"\nTotal: {sum(t for t, _, _ in rows)} sites across {len(rows)} files")


def check(measured):
    baseline = load_baseline()
    if not baseline:
        print(f"No baseline at {BASELINE.relative_to(ROOT)}.", file=sys.stderr)
        print("Create it with: python scripts/check_design_style.py --update",
              file=sys.stderr)
        return 2

    regressions = []
    improvements = []
    for path, counts in sorted(measured.items()):
        allowed = baseline.get(path, {})
        for name, value in sorted(counts.items()):
            limit = allowed.get(name, 0)
            if value > limit:
                regressions.append((path, name, value, limit))
            elif value < limit:
                improvements.append((path, name, value, limit))

    total = sum(sum(counts.values()) for counts in measured.values())
    print(f"Scanned {SCAN_DIRS} under lib/: {total} hardcoded style sites")

    if regressions:
        print("\nRegressions (must use lib/design/ tokens instead):")
        for path, name, value, limit in regressions:
            origin = "new file" if path not in baseline else f"baseline {limit}"
            print(f"  {path}: {name} = {value} (allowed {limit}; {origin})")
        print("\nFix by reading AppSpacing / AppRadius / AppFontSize / "
              "AppDuration / AppElevation or context.palette tokens.")
        return 1

    if improvements:
        print("\nBelow baseline — fold these down with --update:")
        for path, name, value, limit in improvements:
            print(f"  {path}: {name} {limit} -> {value}")

    print("\nNo style regression.")
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--update", action="store_true",
                        help="rewrite the baseline from the current tree")
    parser.add_argument("--report", action="store_true",
                        help="print the worst files without checking")
    args = parser.parse_args()

    if not LIB.exists():
        print(f"Flutter lib dir not found: {LIB}", file=sys.stderr)
        return 2

    measured = collect()
    if args.report:
        report(measured)
        return 0
    if args.update:
        write_baseline(measured)
        return 0
    return check(measured)


if __name__ == "__main__":
    raise SystemExit(main())
